name: CD Pipeline

on:
  workflow_call:
      inputs:
        python-version:
          required: true
          type: string
        PYTHON_DEPLOYMENT_VERSION:
          required: true
          type: string
        ENV:
          required: true
          type: string

env:
  PYTHON_DEPLOYMENT_VERSION: ${{ inputs.python-version }}
  ENV: ${{ inputs.python-version }}
  REPO: ${{ github.event.repository.name }}

jobs:
  build-image:
    name: build-image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build --build-arg PYTHON_VERSION=${{ inputs.python-version }} --build-arg ENV=dev -t ghcr.io/${{ github.repository_owner }}/$REPO_${{ matrix.python-version }}:latest .

      - name: Test with pytest
        run: |
           docker run  ghcr.io/${{ github.repository_owner }}/$REPO_${{ inputs.python-version }}:latest pytest
      - name: Confirmation that all went fine
        run: echo All went ok!
  push-image:
    if: $ENV == $python-version
    permissions:
      contents: read
      packages: write
    name: Push Image
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Docker Image
        env:
            DOCKER_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          docker build --build-arg PYTHON_VERSION=$PYTHON_DEPLOYMENT_VERSION --build-arg ENV=$ENV -t ghcr.io/${{ github.repository_owner }}/$REPO:${DOCKER_BUILD_NUMBER} -t ghcr.io/${{ github.repository_owner }}/$REPO:latest .
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Push Docker Image
        env:
            DOCKER_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/$REPO --all-tags

