# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: list

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ input.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ input.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: flake8 .
    - name: Check with isort
      if: always()
      run: isort . --check
    - name: Check with PyRight
      if: always()
      run: pyright .
    - name: Use Black from external
      if: always()
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "."
        version: "~= 23.9.1"
    - name: Use Black
      if: always()
      run: black . --check --verbose
    - name: Confirmation that all went fine
      run: echo All went ok!
